project:
  type: book

book:
  title: "Healthy Connecticut 20XX"
  subtitle: "State Health Assessment Concept"
  author: "Alexander Senetcky"
  date: "12/18/2024"

  search: true
  repo-url: https://github.com/asenetcky/healthy-ct-concept
  repo-actions: [edit]

  sidebar:
    style: docked

  page-footer:
    left: |
      This is a proof of concept for the CT State Health Assessment.
    right: |
      All information, data and figures are copied out of context or made up.

  chapters:
    - index.qmd
    - acknowledgements.qmd
    - preface.qmd
    - part: "Introduction and Process"
      chapters:
        - intro-overview.qmd
        - intro-methodology.qmd
    - part: "Describing Connecticut"
      chapters:
        - descrb-ct-intro.qmd
        - descrb-ct-social-factors.qmd
    - part: "Maternal, Infant, and Child Health"
      chapters:
        - placeholder/mch-placeholder.qmd
    - part: "Environmental Health"
      chapters:
        - placeholder/eh-placeholder.qmd
    - part: "Drinking Water"
      chapters:
        - placeholder/dw-placeholder.qmd
    - part: "Chronic Diseases"
      chapters:
        - placeholder/dw-placeholder.qmd
    - part: "Infectious Diseases"
      chapters:
        - placeholder/id-placeholder.qmd
    - part: "Behavioral Health, Trauma, and Injury"
      chapters:
        - placeholder/bhti-placeholder.qmd
    - part: "Health Systems"
      chapters:
        - placeholder/hs-placeholder.qmd
    - part: "Climate and Health"
      chapters:
        - placeholder/ch-placeholder.qmd
    - part: "Navigating Health Equity"
      chapters:
        - placeholder/nhe-placeholder.qmd
    - part: "Meta"
      chapters:
        - data-datalayer.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



