# Acknowledgements {.unnumbered}

## Connecticut Department of Public Health

**J. Smith Commish, MD, MPH **
*Acting Commisioner*

**J. Smith Dep, MPH, LNHA**
*Deputy Commisioner*

---

This Connecticut State Health Assessment was developed by the Connecticut Department of Public Health with the assistance of the Connecticut Health Improvement Coalition, and its Action Teams and Advisory Council.

This Assessment is the result of more than a year of dedicated and
collaborative effort of DPH staff, staff from several other State
agencies, and subject matter experts throughout the state who analyzed
and contributed data and reviewed multiple iterations of this
document as it evolved. This Assessment would not have been possible 
without their expertise and commitment to this project.

We gratefully acknowledge the contributions of our consultant,

> **Health Resources in Action**  
> Boston, MA

for facilitating collaborative activities of the State Health 
Improvement Coalition and its Advisory Council, and for assisting with
compiling this Assessment in cooperation with DPH.

---


*This publication was supported by the Preventive Health & Health Services Block
Grant (PHHSBG), Grant # 1NB01OT009192-01-00, funded by the Centers for Disease
Control and Prevention. Its contents are solely the responsibility of the
authors and do not necessarily represent the official views of the Centers for
Disease Control and Prevention or the Department of Health and Human Services.*
