{{< include preamble.Rmd >}}

# Methodology

The Healthy Connecticut 2025: State Health Assessment was
ultimately guided by Connecticut’s vision for health equity. The
health indicators selected to be presented in the assessment
reflect the social determinants of health that are impacting
residents and highlight where health is experienced differently
based on geographic or demographic characteristics.

The development of this assessment incorporated the Mobilizing
for Action through Planning and Partnerships (MAPP) framework
and Public Health Accreditation Board (PHAB) standards and
measures. A cross-disciplinary team of internal and external
stakeholders was engaged to develop a vision for Healthy
Connecticut 2025 and to prioritize a list of health indicators for
inclusion in the report. In addition, community members were
provided opportunities to contribute to the development of
the assessment through surveys and focus groups, and finally
through a public comment period.

## Engagement Process

{{< lipsum 1 >}}

### Community Survey

{{< lipsum 1 >}}

These populations of focus included:

- Parents of children with special healthcare needs

- People receiving services from the Connecticut Department of Social Sevices

- Patients of Deferally-Qualified Health Centers (FQHCs)

### Community Focus Groups

{{< lipsum 1 >}}

- Aging Adults

- Black/African-American Women

- Families Affected by Alzheimer's

- Families Affected by Autism

- Families of Children with Special Healthcare Needs

- Formerly Incarcerated Persons

- Hispanic Community

- Immigrants and Refugees

- LGBTQ Aging Adults

- LGBTQ Younger Adults

- Veterans and their Families


### Public and Partner Input

{{< lipsum 2 >}}

### Assets and Resources

As CT DPH teams gathered and analyzed data for the assessment,
they also compiled a list of programmatic and state-wide
assets. Additionally, through an analysis of local community
health assessments and hospital health needs assessments,
and partner input, community assets were added to develop a
comprehensive list. A high level description of community assets
and resources is available in Appendix B. A more detailed
listing of identified assets, including the analysis of the local
community health and hospital health assessments is contained
in a companion document “Assets and Resources” available on
the Coalition website. This document will serve as a dynamic
and continuously updated resource for mapping assets to
intentionally developed collaborative strategies. 

## Kinds of Data Presented in the Assessment

The State Health Assessment presents many kinds of data visualized in graphs,
tables, and maps. Here are some examples of data types included in this report
and what they mean.

:::{.callout-important}
Please note we can do much prettier tables in code, and in fact
I'll insist on it, but for demonstration purposes, we'll use straight markdown.
:::

| Data Type | Answers the Question | Definition | Example |
|------------|-----------|---------|------| ------- |
| Census     |  How many people are/ have ____?  |  An official count of a population, typically recording various details of individuals   | A total of 3.5 million people live in Connecticut. |
| Prevalence |  What percentage of people have ____? |   Describes how many people have a disease or condition among an entire group of people. Often you will see this as a rate or percentage.  | About 200 of every 100,000 people has diabetes.|
| Incidence  |    How many new cases of ____ happened in a period of time? | This refers to the number of individuals who develop a specific disease or experience a specific health-related event during a particular time period (such as a month or year) | The incidence of infection went down from X cases per 10,000 to just Y cases.  |


{{< lipsum 1 >}}

## Limitations of assessment

{{< lipsum 1 >}}

## Connecticut Maps

Below is an example map made using the `ggplot2` package.  `ggplot2` are static
and by keeping them static, this book can be converted into multiple different
formats like pdf, word etc... If users choose to forgo those options and stick
with this as primarily a website and .html, than interactive maps/visuals
can be added as well.  In my opinion, I think this document should stay
static, and then other tools/platforms (like CT Open Data Portal) can tap into 
the same data streams and they can offer deeper interactive dives into the data.




```{r}
#| echo: false
#| message: false
#| warning: false
#| label: fig-random-map
#| fig-cap: "source: @placeholder1"


# library(leaflet)
# 
# leaflet() |> 
#   addProviderTiles(providers$CartoDB) |> 
#   setView(-72.699997, 41.599998, zoom = 9)

library(tigris)
library(RSocrata)

ct_county_disease_data <- 
  RSocrata::read.socrata("https://data.ct.gov/resource/4rss-apm8.json") |> 
  group_by(ceprcode) |> 
  summarize(n = n()) |> 
  filter(!is.na(ceprcode))

ct_sf <- 
  tigris::counties(
    state = "09", 
    cb = TRUE, 
    class = "sf",
    progress_bar = FALSE
  ) 

random_cepr_disease_data <- 
  ct_sf |> 
  left_join(
    ct_county_disease_data, 
    by = join_by(COUNTYFP == ceprcode)
  )
  
ggplot(random_cepr_disease_data) +
  geom_sf(aes(fill = n)) +
  geom_sf_text(aes(label = COUNTYFP), col = "black",  size = 4.0) +
  scale_fill_viridis_c(direction = -1) +
  theme_void() +
  labs(
    title = "This is a Map Using random CT Open Data",
    subtitle = "Subtitle",
    fill = glue::glue("Reportable Disease
                      Count"),
    caption = 
    "This is thrown together, but we can create a unifying theme, with variants, for all visuals"
  ) +
  theme(
  # plot.title = element_text(size =11),
  legend.position = c(0.73,0.14),
  legend.direction = "horizontal",
  # legend.title = element_text(size = 8),
  # legend.text = element_text(size=8),
  # legend.key.size = unit(0.80, "line")
)

```

