# State Health Assessment Overview

## What is the State Health Assessment?

The 2019 Connecticut State Health Assessment is an update on the health status
of Connecticut residents with a focus on the social determinants of health that
are having the greatest impact on health outcomes. The assessment provides the
basis for the Connecticut State Health Improvement Plan, which together make up
the state health planning framework Healthy Connecticut 2025.

The purpose of the assessment is to provide the public, policy leaders,
partners, and stakeholders with information on the health of the Connecticut
population to develop a shared understanding of health issues and inform
data-driven decision making and program planning. This state health assessment
is an important tool to help identify the underlying conditions and factors that
influence health, reflect on existing services and policies, and inform future
public health planning for the benefit of all Connecticut communities.

## Visions for Health Equity

Connecticut has a bold vision for Healthy Connecticut 2025. More
specifically, the Connecticut Department of Public Health (CT
DPH) and partners envision the following: 

---

> Through effective assessment, prevention, and
> policy development, the Connecticut Department
> of Public Health and its stakeholders and partners
> provide every Connecticut resident equitable
> opportunities to be healthy throughout their
> lifetimes and are accountable to making
> measurable improvements toward health equity.

---

This vision lifts up a number of guiding principles that we uphold
to center health equity:

- **A focus on every Connecticut resident:** We strive for
all Connecticut residents to experience optimal health
and wellbeing.*

- Attention to the health needs of residents **throughout
their lifetimes.**

- **A need to collaborate as stakeholders and partners:**
No one entity can advance health equity in isolation. A
multi-sector and community-engaged approach is necessary
to effectively understand the interconnected social
determinants that impact health, and effectively address
the practices, policies, and systems that support them.

- A multi-pronged approach through **assessment, prevention,
policy development and accountability to achieve
measurable improvements in health equity.**

More information about health equity, health disparities, and
the Social Determinants of Health can be found in the Describing
Connecticut chapter.
