# Preface {.unnumbered}

## Letter from the Commissioner

**To Our Residents and Public Health Partners:**

The Connecticut Department of Public Health is pleased to present the Healthy
Connecticut 2025 State Health Assessment. Subject matter experts from the
Connecticut Department of Public Health (CT DPH), in collaboration with other
state agencies, statewide partners and community organizations, have assembled
data reflecting on the health and safety of Connecticut residents. The last such
document was published in 2014.

The State Health Assessment establishes the health status of the state, and will
inform the prioritization and development of the next Healthy Connecticut 2025
State Health Improvement Plan (SHIP). This plan will serve as a 5-year roadmap
for promoting and advancing population health in our State. Statewide partners
from the Connecticut Health Improvement Coalition, along with CT DPH, will begin
the collaborative development of the SHIP in January 2020.

While Connecticut is a healthy state overall, this assessment highlights the
challenges faced around achieving health equity for all our residents. The
Centers for Disease Control and Prevention (CDC) states that health equity is
achieved when every person has the opportunity to “attain his or her full health
potential” and no one is “disadvantaged from achieving this potential because of
social position or other socially determined circumstances.” CT DPH is committed
to enhancing health equity for our state; this document is an affirmation that
equitable access to healthcare and addressing those social conditions that
impact health is a basic human right.

The Healthy Connecticut 2025 initiative will focus on making the connection
between social determinants and health outcomes. To experience success with
these efforts we must prioritize examining the impact of social, behavioral and
environmental factors on health to better inform policies and promote systemic
change, while exploring collaborative place-based initiatives with our municipal
and local health partners. It is our hope that we continue to work together to
address the needs of Connecticut residents and afford every single person the
opportunity to be as healthy as possible.

We look forward to collaborating with you in the future on this important work.

Sincerely,

**J. Smith Commish, MD, MPH**  
*Acting Commissioner*

